name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    # 构建环境使用 ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      # 将打包内容发布到 Github Page
      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env: 
          ACCESS_TOKEN: ${{ secrets.VUE_PRESS }}
          BUILD_DIR: docs/.vuepress/dist
          BUILD_SCRIPT: yarn && yarn build